all: task1 task2 task3 task4 bezier

task1: task1.asm
	nasm -f bin -o t1.com task1.asm

task2: task2.asm
	nasm -f bin -o t2.com task2.asm

task3: task3.asm
	nasm -f bin -o t3.com task3.asm

task4: task4.asm
	nasm -f bin -o t4.com task4.asm

bezier: bezier.asm
	nasm -f bin -o bezier.com bezier.asm
