@startuml

participant "Пользовательское\nприложение" as app
participant "Окружение" as env
participant "Дизассемблер" as dasm

app -> env : Путь к исполняемому файлу
alt Прочитан успешно
  env -> app : Содержимое исполняемого файла
else Ошибка чтения
  env -> app : Сообщение об ошибке
end

app -> dasm : Содержимое исполняемого файла
alt Дизассемблирован успешно
  dasm -> app : Промежуточное представление,\nметаданные
else Ошибка дизассемблирования
  dasm -> app : Сообщение об ошибке
end

loop для каждого анализатора
  create "Анализатор" as anlz
  app -> anlz : Метаданные, внешнее окружение

  alt Анализатор применим
    anlz -> app : Функция анализа
  else Анализатор не применим
    anlz -> app : Сообщение об ошибке
  end
end

create "Контекст" as ctx
app -> ctx : Функции анализа\nприменимые к данной конфигурации

alt Зависимости разрешены успешно
  ctx -> app : Контекст анализа
else Ошибка разрешения зависимостей
  ctx -> app : Сообщение об ошибке
end

app -> ctx : Промежуточное представление
app -> ctx : Требуемые типы результатов

loop для каждого анализатора
  ctx -> anlz : Метаданные
  alt Выполнение завершено успешно
    anlz -> ctx : Результаты анализа
  else Ошибка анализа
    anlz -> ctx : Сообщение об ошибке
  end
end

alt Анализаторы завершились успешно
  ctx -> app : Результаты анализа
else Ошибка анализа
  ctx -> app : Сообщение об ошибке
end

@enduml
