@startuml

participant "Пользовательское\nприложение" as app

create "Контекст" as ctx
app -> ctx : Путь к исполняемому файлу,\nинстанции анализаторов (функции)

create "Окружение" as env
ctx -> env : Путь к исполняемому файлу
alt Прочитан успешно
  env -> ctx : Содержимое исполняемого файла
else Ошибка чтения
  env -> ctx : Сообщение об ошибке
end

create "Дизассемблер" as dasm
ctx -> dasm : Содержимое исполняемого файла
alt Дизассемблирован успешно
  dasm -> ctx : Промежуточное представление,\nметаданные
else Ошибка дизассемблирования
  dasm -> ctx : Сообщение об ошибке
end

loop для каждого анализатора
  create "Анализатор" as anlz
  ctx -> anlz : Метаданные
  anlz -> env : Запрос внешних параметров конфигурации\n(файлов, переменных окружения)
  env -> anlz : Внешние параметры конфигурации
  alt Анализатор применим
    anlz -> ctx : Функция анализа
    ctx -> anlz : Зависимости
    alt Выполнение завершено успешно
      anlz -> ctx : Результаты анализа
    else Ошибка анализа
      anlz -> ctx : Сообщение об ошибке
    end
  else Анализатор не применим
    anlz -> ctx : Сигнал пропуска исполнения\nданного анализатора
  end
end

alt Анализ завершен успешно
  ctx -> app : Результаты анализа
else Ошибка анализа
  ctx -> app : Сообщение об ошибке
end

@enduml

