@startuml
skinparam defaultTextAlignment center

|Контекст исполнения|
start
:Помещение\nанализатора R в\nстек исполнения;
repeat
if (Результат R\nвычислен заранее?) then (да)
  :Загрузка\nсохраненного R;
else (нет)
  :Проверка\nстека исполнения;
  if (Встречается ли\nодин и тот же\nанализатор дважды?) then (да)
    :Вывод ошибки о\nрекурсивной\nзависимости;
    stop
  else (нет)
    |Анализатор|
    :Исполнение\nанализатора;
    if (Требуется\nневычисленная\nзависимость D?) then (да)
      |Контекст исполнения|
      :Помещение\nанализатора\nтипа D в стек\nисполнения;
    else (нет)
      |Анализатор|
      if (Требуется\nвычисленная\nзависимость D?) then (да)
        |Контекст исполнения|
        :Загрузка\nсохраненного D;
      else (нет)
      endif
      |Анализатор|
      :Формирование\nрезультата R;
      |Контекст исполнения|
      :Сохранение R;
      :Извлечение\nанализатора из\nстека исполнения;
    endif
  endif
endif
repeat while (Стек исполнения пуст?) is (нет)
->да;
stop

@enduml
