@startuml
skinparam defaultTextAlignment center

start
partition "Подготовка анализатора" {
  :Деконструирование типа\nфункции анализатора (D -> R);
  :Проверка рекурсивных зависимостей;
  if (Рекурсивные зависимости найдены?) then (да)
    :Вывод ошибки;
  else (нет)
    :Поиск зависимостей\nсреди выходных типов\nостальных анализаторов;
    if (Зависимости найдены?) then (да)
    else (нет)
      :Вывод ошибки;
    endif
  endif
  stop
}
partition "Исполнение анализатора D -> R" {
  start
  if (Результат R уже вычислен?) then (нет)
    while (Есть невычисленная\nзависимость D (D2, ...)?) is (да)
      :Исполнение\nанализатора D;
    endwhile (нет)
    :Загрузка сохраненной\nзависимости D;
    :Выполнение функции\nанализатора (D -> R);
    :Сохраненение R;
  else (да)
  endif
  :Возвращение сохраненного R;
  stop
}

@enduml
